### ISSUE TITLE
Why not PR instead of fork?

### ISSUE THREAD

**Issue by Techjar** [CJCrafter/VivecraftSpigot#3]
I think it would benefit all parties if we merged the improvements into our main plugin. Takes the maintenance burden off your shoulders and makes things less confusing to users. Also, I wasn't aware Spigot's metadata system was broken. Can you elaborate more on that?

**Comment by CJCrafter** [comment]
Hey @Techjar, I tried making PRs to solve my issues with Vivecraft_Spigot_Extentions, but [they were largely ignored](https://github.com/jrbudda/Vivecraft_Spigot_Extensions/pulls?q=is%3Apr+author%3ACJCrafter). 

I started with a rewrite of your entire plugin to use modern standards... This would have fixes most of the maintenance and compatibility issues you faced. I also made sure to document my changes to reduce any friction. Unfortunately, that PR was ignored completely.

Assuming you weren't willing to merge a rewrite, I made a small PR to allow your API to work for other plugins. This was also ignored.

I tried contacting you all on both GitHub and Discord (my discord tag is `cjcrafter`, you can search for my messages). Unfortunately, the only plugin developers to add VR support to their plugin was for me to hard fork the repo.

**Comment by CJCrafter** [comment]
If you are interested in me merging with branch, let me know.
